# Generated by Django 6.1.1 on 2026-10-07 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('especialidad', models.CharField(max_length=200)),
                ('biografia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('observaciones_medicas', models.TextField()),
                ('fecha_alta', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sala', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateTimeField()),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.entrenador')),
            ],
        ),
    ]
